2025-02-06 16:32:49.075 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-06 16:32:49.076 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-06 16:32:49.077 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-02-06 16:32:58.564 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276922026592] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:33:01.395 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Integration repo "browser mod" is not installed!
2025-02-06 16:33:11.177 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276922026592] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:33:21.733 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276922026592] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:33:50.182 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('upnp', '01JK4VKM9ZA7YQDBQ4VKDWD7BF'): 1050843.271869912}
2025-02-06 16:34:50.236 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('upnp', '01JK4VKM9ZA7YQDBQ4VKDWD7BF'): 1050843.271869912}
2025-02-06 16:35:50.298 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('upnp', '01JK4VKM9ZA7YQDBQ4VKDWD7BF'): 1050843.271869912}
2025-02-06 16:36:50.362 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('upnp', '01JK4VKM9ZA7YQDBQ4VKDWD7BF'): 1050843.271869912}
2025-02-06 16:37:05.339 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276922026592] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:41:11.665 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276179426256] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:41:28.771 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276179426256] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:47:11.857 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276193770320] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 16:56:23.684 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165395360] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:01:29.458 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276193767872] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:06:30.002 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165397520] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:11:38.254 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172627328] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:16:39.426 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165402992] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:22:30.768 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172630352] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:27:36.463 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165402704] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:34:14.264 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172634096] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:40:09.508 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165406736] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:45:22.326 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165408176] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:50:23.160 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172627184] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 17:53:21.055 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172620560] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 18:07:32.240 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165409904] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 18:11:37.025 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172631792] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 18:20:35.535 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165395648] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 18:38:02.913 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:ca389dbe-b5a5-48eb-97f6-36e4ef1079a5, reason: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2025-02-06 18:47:52.317 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172634816] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 18:57:24.701 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165400112] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 19:07:02.912 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:cd63620a-866f-441e-a648-02222e35f44c, reason: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2025-02-06 19:36:02.912 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:1878ee93-5e31-424a-9b56-582ac52822d8, reason: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2025-02-06 19:52:29.827 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172629488] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 20:05:02.912 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:a88f8034-4501-4c6e-a9f0-48779a300464, reason: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2025-02-06 20:27:22.171 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172635392] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 20:36:43.661 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172626320] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 21:29:36.886 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172619840] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 21:37:33.590 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165399536] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 21:50:16.231 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172624016] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 21:55:30.521 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154342064] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 21:58:32.621 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154340192] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 22:13:13.850 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172627904] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 22:21:28.020 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154349552] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-06 22:22:52.716 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154342784] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 01:39:37.467 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165398816] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 02:22:53.600 ERROR (Thread-5) [pychromecast.socket_client] [Living room Chromecast(192.168.1.86):8009] Failed to connect to service HostServiceInfo(host='192.168.1.86', port=8009), retrying in 5.0s
2025-02-07 04:00:07.894 ERROR (Thread-8) [pychromecast.socket_client] [Home group(192.168.1.73):32009] Error reading from socket: socket connection broken
2025-02-07 04:00:07.896 ERROR (Thread-8) [pychromecast.socket_client] [Home group(192.168.1.73):32009] Failed to connect to service HostServiceInfo(host='192.168.1.73', port=32009), retrying in 5.0s
2025-02-07 04:00:49.028 ERROR (Thread-7) [pychromecast.socket_client] [Living room Speaker(192.168.1.73):8009] Failed to connect to service HostServiceInfo(host='192.168.1.73', port=8009), retrying in 5.0s
2025-02-07 11:44:00.187 WARNING (Thread-2 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.1.88, code The connection was lost
2025-02-07 12:08:39.138 WARNING (Thread-2 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2025-02-07 12:08:39.140 WARNING (Thread-2 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.1.88, code UNKNOWN_ERROR
2025-02-07 12:08:39.140 WARNING (Thread-2 (_thread_main)) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2025-02-07 12:08:39.140 WARNING (Thread-2 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.1.88, code UNKNOWN_ERROR
2025-02-07 13:33:37.371 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165401264] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 13:58:34.821 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172483184] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 14:07:02.393 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143306448] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 15:54:19.127 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154345664] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:04:08.666 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172630928] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:26:49.059 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154341920] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:36:55.996 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154347536] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:42:47.474 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143302128] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:48:02.564 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276193769312] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:53:10.288 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172473536] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 16:58:33.867 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172631936] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:04:18.411 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143295360] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:09:28.933 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165405152] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:16:04.894 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276469306208] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:21:16.860 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143293920] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:26:54.770 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172622144] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:29:02.463 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172631936] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:36:08.101 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172635392] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:44:33.706 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154346384] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 17:53:02.996 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172474544] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 18:01:34.765 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276469310816] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 18:20:19.093 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172629920] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 18:29:46.148 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276154338896] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 19:01:00.636 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143298528] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 19:14:19.454 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276165399824] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 19:21:45.190 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172477568] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 19:53:43.136 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276179428128] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 20:01:48.726 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172481312] Error handling message: Unknown error (unknown_error) Sean from 192.168.1.70 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 21:09:26.009 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172477280] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 21:17:56.553 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172486784] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 21:39:00.891 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172634528] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 21:48:07.412 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143298672] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 21:56:28.774 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276172628480] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-07 22:04:49.424 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276143294496] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-08 01:20:10.772 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140276142672624] Error handling message: Unknown error (unknown_error) Sean from 127.0.0.1 (Home Assistant/2025.1 (io.robbie.HomeAssistant; build:2025.1073; iOS 18.3.0))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
2025-02-08 02:46:54.043 ERROR (Thread-8) [pychromecast.socket_client] [Home group(192.168.1.73):32009] Error reading from socket: socket connection broken
2025-02-08 02:46:54.050 ERROR (Thread-8) [pychromecast.socket_client] [Home group(192.168.1.73):32009] Failed to connect to service HostServiceInfo(host='192.168.1.73', port=32009), retrying in 5.0s
2025-02-08 02:47:33.285 ERROR (Thread-7) [pychromecast.socket_client] [Living room Speaker(192.168.1.73):8009] Failed to connect to service HostServiceInfo(host='192.168.1.73', port=8009), retrying in 5.0s
2025-02-08 02:48:41.856 ERROR (Thread-5) [pychromecast.socket_client] [Living room Chromecast(192.168.1.86):8009] Failed to connect to service HostServiceInfo(host='192.168.1.86', port=8009), retrying in 5.0s
2025-02-08 06:14:31.912 ERROR (MainThread) [pubnub] session.request exception: Connector is closed.
